// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI/міграції: пряме (unpooled) з'єднання, якщо задано DIRECT_URL
    // (потрібно для Neon — міграції не люблять pgbouncer). Локально DIRECT_URL
    // нема → використовуємо DATABASE_URL. Рантайм застосунку підключається
    // окремо через driver-adapter у PrismaService (теж DATABASE_URL).
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
